[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.10"

[[repos.hooks]]
id = "ruff-check"
types_or = ["python", "pyi"]
args = ["--fix"]
stages = ["pre-commit"]
priority = 1

[[repos.hooks]]
id = "ruff-format"
types_or = ["python", "pyi"]
stages = ["pre-commit"]
priority = 2